# Generated by Django 4.1.8 on 2023-04-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USER',
            new_name='USERS',
        ),
    ]
