# Generated by Django 4.1.8 on 2023-04-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('password_repeat', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='USERS',
        ),
    ]
