# Generated by Django 4.1.8 on 2023-05-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_article_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
